spring:
  application:
    name: SpecShield
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: specshield-executor
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.dpw.specshield.model
  mongodb:
    host: ${SPRING_DATA_MONGODB_HOST:localhost}
    port: ${SPRING_DATA_MONGODB_PORT:27017}
    database: ${SPRING_DATA_MONGODB_DATABASE:specshield}

server:
  servlet:
    context-path: /specshield
  port: 9000

logging:
  level:
    com.dpw.specshield: DEBUG
    org.springframework.data.mongodb: ERROR
    org.springframework.kafka: ERROR

# Custom configuration
specshield:
  kafka:
    topics:
      test-execution: test-execution-requests

swagger:
  url: classpath:resource_swagger.json