spring:
  application:
    name: SpecShield
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/specshield}
      database: specshield

server:
  servlet:
    context-path: /specshield
  port: 9000

logging:
  level:
    com.dpw.specshield: DEBUG
    org.springframework.data.mongodb: DEBUG